-- Irregular Verbs Database Setup
-- Run this SQL in your Supabase SQL Editor

-- Create irregular_verbs table
CREATE TABLE IF NOT EXISTS irregular_verbs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  base_form TEXT NOT NULL,
  past_simple TEXT NOT NULL,
  past_participle TEXT NOT NULL,
  meaning_uz TEXT NOT NULL,
  is_dual_form BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE irregular_verbs ENABLE ROW LEVEL SECURITY;

-- Create policy to allow read access
CREATE POLICY "Anyone can read irregular verbs" ON irregular_verbs
  FOR SELECT USING (true);

-- Insert all irregular verbs
INSERT INTO irregular_verbs (base_form, past_simple, past_participle, meaning_uz, is_dual_form) VALUES
('be', 'was/were', 'been', 'bo‘lmoq', false),
('beat', 'beat', 'beaten', 'urmoq', false),
('become', 'became', 'become', 'aylanmoq', false),
('begin', 'began', 'begun', 'boshlamoq', false),
('bite', 'bit', 'bitten', 'tishlamoq', false),
('blow', 'blew', 'blown', 'puflamoq', false),
('break', 'broke', 'broken', 'sindirmoq', false),
('bring', 'brought', 'brought', 'keltirmoq', false),
('build', 'built', 'built', 'qurmoq', false),
('buy', 'bought', 'bought', 'sotib olmoq', false),
('catch', 'caught', 'caught', 'tutmoq', false),
('choose', 'chose', 'chosen', 'tanlamoq', false),
('come', 'came', 'come', 'kelmoq', false),
('cost', 'cost', 'cost', 'turmoq', false),
('cut', 'cut', 'cut', 'kesmoq', false),
('do', 'did', 'done', 'qilmoq', false),
('draw', 'drew', 'drawn', 'chizmoq', false),
('drink', 'drank', 'drunk', 'ichmoq', false),
('drive', 'drove', 'driven', 'haydamoq', false),
('eat', 'ate', 'eaten', 'yemoq', false),
('fall', 'fell', 'fallen', 'yiqilmoq', false),
('feel', 'felt', 'felt', 'his qilmoq', false),
('fight', 'fought', 'fought', 'jang qilmoq', false),
('find', 'found', 'found', 'topmoq', false),
('fly', 'flew', 'flown', 'uchmoq', false),
('forget', 'forgot', 'forgotten', 'unutmoq', false),
('get', 'got', 'got', 'olmoq', false),
('give', 'gave', 'given', 'bermoq', false),
('go', 'went', 'gone', 'bormoq', false),
('grow', 'grew', 'grown', 'o‘smoq', false),
('hang', 'hung', 'hung', 'osib qo‘ymoq', false),
('have', 'had', 'had', 'ega bo‘lmoq', false),
('hear', 'heard', 'heard', 'eshitmoq', false),
('hide', 'hid', 'hidden', 'yashirmoq', false),
('hit', 'hit', 'hit', 'urmoq', false),
('hold', 'held', 'held', 'ushlamoq', false),
('hurt', 'hurt', 'hurt', 'jarohat qilmoq', false),
('keep', 'kept', 'kept', 'saqlamoq', false),
('know', 'knew', 'known', 'bilmoq', false),
('leave', 'left', 'left', 'ketmoq', false),
('lend', 'lent', 'lent', 'qarz bermoq', false),
('let', 'let', 'let', 'ruxsat bermoq', false),
('lie', 'lay', 'lain', 'yotmoq', false),
('light', 'lit', 'lit', 'yoritmoq', false),
('lose', 'lost', 'lost', 'yo‘qotmoq', false),
('make', 'made', 'made', 'yasamoq', false),
('mean', 'meant', 'meant', 'anglatmoq', false),
('meet', 'met', 'met', 'uchrashmoq', false),
('pay', 'paid', 'paid', 'to‘lamoq', false),
('put', 'put', 'put', 'qo‘ymoq', false),
('read', 'read', 'read', 'o‘qimoq', false),
('ride', 'rode', 'ridden', 'minmoq', false),
('ring', 'rang', 'rung', 'jiringlamoq', false),
('rise', 'rose', 'risen', 'ko‘tarilmoq', false),
('run', 'ran', 'run', 'yugurmoq', false),
('say', 'said', 'said', 'aytmoq', false),
('see', 'saw', 'seen', 'ko‘rmoq', false),
('sell', 'sold', 'sold', 'sotmoq', false),
('send', 'sent', 'sent', 'yubormoq', false),
('shine', 'shone', 'shone', 'yaltiramoq', false),
('shoot', 'shot', 'shot', 'otmoq', false),
('show', 'showed', 'shown', 'ko‘rsatmoq', false),
('shut', 'shut', 'shut', 'yopmoq', false),
('sing', 'sang', 'sung', 'qo‘shiq aytmoq', false),
('sit', 'sat', 'sat', 'o‘tirmoq', false),
('sleep', 'slept', 'slept', 'uxlamoq', false),
('speak', 'spoke', 'spoken', 'gaplashmoq', false),
('spend', 'spent', 'spent', 'sarflamoq', false),
('stand', 'stood', 'stood', 'turmoq', false),
('steal', 'stole', 'stolen', 'o‘g‘irlamoq', false),
('swim', 'swam', 'swum', 'suzmoq', false),
('take', 'took', 'taken', 'olmoq', false),
('teach', 'taught', 'taught', 'o‘qitmoq', false),
('tear', 'tore', 'torn', 'yirtmoq', false),
('tell', 'told', 'told', 'aytmoq', false),
('think', 'thought', 'thought', 'o‘ylamoq', false),
('throw', 'threw', 'thrown', 'otmoq', false),
('understand', 'understood', 'understood', 'tushunmoq', false),
('wake', 'woke', 'woken', 'uyg‘otmoq', false),
('wear', 'wore', 'worn', 'kiymoq', false),
('win', 'won', 'won', 'yutmoq', false),
('write', 'wrote', 'written', 'yozmoq', false),
('burn', 'burned/burnt', 'burned/burnt', 'kuymoq', true),
('dream', 'dreamed/dreamt', 'dreamed/dreamt', 'tush ko‘rmoq', true),
('learn', 'learned/learnt', 'learned/learnt', 'o‘rganmoq', true),
('smell', 'smelled/smelt', 'smelled/smelt', 'hidini sezmoq', true),